# Generated by Django 3.1.7 on 2021-03-05 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='place',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='zipcode',
            new_name='postal_code',
        ),
    ]
