# Generated by Django 3.1.7 on 2021-03-05 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_images',
            name='slug',
        ),
    ]
